### ISSUE TITLE
Question about word list

### ISSUE THREAD

**Issue by sourencho** [gagikm/bardl#2]
This is awesome! Thanks so much for putting it together :)

I forked your repo to make a western armenian version. I just had one question.
What's the difference between these two lists? It's hard to tell with the minified js

https://github.com/gagikm/bardl/blob/59103e56788ed9e94fa25f2e45455dc79c1ffaf3/Wordle%20-%20A%20daily%20word%20game_files/main.e65ce0a5.js#L950-L951

**Comment by gagikm** [comment]
Hi Souren,

I got this code from the original version and had to figure that out too. The first list includes the actual word-of-the-days, the second list are valid words that will not be word-of-the-day. BTW you should fork the other branch, it's more updated.

Thanks for working on a western one. We could even add a toggle for Western/Eastern and just switch lists.
