### ISSUE TITLE
"Սառաց" բառ հայերենում չկա

### ISSUE THREAD

**Issue by arsendovlatyan** [gagikm/bardl#3]
Ողջույն,

Կարծում եմ "սառաՑ" բառը սխալմամբ է հայտնվել բառարանում, ենթադրում եմ պիտի լիներ "սառաԾ"։

![Screenshot_20220521-012847_Samsung Internet](https://user-images.githubusercontent.com/1083615/169615643-531e7006-5b59-4eed-bb43-9c2fc00d561f.jpg)

Շնորհակալ եմ։
Արսեն

**Comment by gagikm** [comment]
Շնորհակալություն

**Comment by gagikm** [comment]
սառաց --> սառած
